### PR TITLE
Added a site-specific make file and profile-like central module to ma…

### PR DESCRIPTION
**Pull request by ZeiP**
…ke customising a KADA site easier without completely breaking the backwards-compatibility.

This is trying to solve the problem of having to immediately branch off a local copy of the make file and profile in order to enable the site-specific theme and make any other customisations.

The idea is to add any site-specific modules to conf/site.make and let conf/kadaproject.make be as-is. Additionally new directories are added for per-site modules and features; and a new ”profile-like” central module that is enabled by the profile is added for enabling necessary per-site features.

### CODE REVIEW

**Comment by juhaniemi** [comment]
In general this is a very good idea. 

One suggestion: Would it be simpler if kada_site would have the site-specific makefile (kada_site.make)? Customizations would live only in one place.

**Comment by ZeiP** [comment]
@juhaniemi, good point. That would probably work just as well. However IMO it would be more clear if the site-specific make file resides in the same place as the distribution make file (and settings.php versions etc.) Another option would be to move the distribution make file under the profile – I wonder if that'd work?

**Comment by kekkis** [comment]
If #31 will be merged, the update to the OL library in kadaproject.make will conflict as well. I have been using this as an applied patch on Jyväskylä and have liked the way of working so far, with one exception. 

Apparently there is no way to "unset" projects in makefiles, so the `site.make` file cannot handle for example replacing the Sarnia module (whose download method is set in `kadaproject.make` to `git`) with a more recent stable version. For that I had to touch the `kadaproject.make` anyway.

**Comment by ZeiP** [comment]
It seems we have two seconds for the feature, so perhaps I can be bold and merge this. I resolved a few conflicts from the PR.

**Pull request merged**
